// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvy6oBz-AspycR2z84W2woQeQiiK4INMQ',
    appId: '1:733719165364:web:902291c923aebeb91d1ae1',
    messagingSenderId: '733719165364',
    projectId: 'eventify-c1bae',
    authDomain: 'eventify-c1bae.firebaseapp.com',
    databaseURL: 'https://eventify-c1bae-default-rtdb.firebaseio.com',
    storageBucket: 'eventify-c1bae.firebasestorage.app',
    measurementId: 'G-NKBJ81M2LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3-w7ZCyEkFiwslBXvvENh0LEGMZgsRpk',
    appId: '1:733719165364:android:f7b299725647229f1d1ae1',
    messagingSenderId: '733719165364',
    projectId: 'eventify-c1bae',
    databaseURL: 'https://eventify-c1bae-default-rtdb.firebaseio.com',
    storageBucket: 'eventify-c1bae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ERHLkfIcmFgyzzV_pMievGADsAbd--E',
    appId: '1:733719165364:ios:022c766a60c885141d1ae1',
    messagingSenderId: '733719165364',
    projectId: 'eventify-c1bae',
    databaseURL: 'https://eventify-c1bae-default-rtdb.firebaseio.com',
    storageBucket: 'eventify-c1bae.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ERHLkfIcmFgyzzV_pMievGADsAbd--E',
    appId: '1:733719165364:ios:022c766a60c885141d1ae1',
    messagingSenderId: '733719165364',
    projectId: 'eventify-c1bae',
    databaseURL: 'https://eventify-c1bae-default-rtdb.firebaseio.com',
    storageBucket: 'eventify-c1bae.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvy6oBz-AspycR2z84W2woQeQiiK4INMQ',
    appId: '1:733719165364:web:331dc088024307d71d1ae1',
    messagingSenderId: '733719165364',
    projectId: 'eventify-c1bae',
    authDomain: 'eventify-c1bae.firebaseapp.com',
    databaseURL: 'https://eventify-c1bae-default-rtdb.firebaseio.com',
    storageBucket: 'eventify-c1bae.firebasestorage.app',
    measurementId: 'G-27NW6FXSHD',
  );
}
